#!/usr/bin/env node

'use strict';
const program = require('commander');

const crypto = require('crypto');
const axios = require('axios');

program
    .option('-t, --testnet', 'use testnet')
    .option('-v, --verbose', 'show the request')
    .parse(process.argv);

var tokenToAvoidCache = crypto.randomBytes(32).toString('hex');
var env;

if (program.testnet) {
    env = 'testnet';
} else {
    env = 'production';
}

var url = 'https://s3.amazonaws.com/data-' + env + '-walltime-info/'
    + env + '/dynamic/walltime-info.json?nocache=' + tokenToAvoidCache;

if (program.verbose) {
    console.log('GET ' + url);
    console.log();
}

axios.get(url)
    .then(response => {
        console.log(response.data);
    })
    .catch(error => {
        console.error(error);
    });
