#!/usr/bin/env node

'use strict';
const program = require('commander');

program
    .version('1.0.0')
    .description('Walltime CLI is the Walltime Digital Assets Exchange Command Line Interface. With this app, you can easily retrieve market info and manipulate your account.')
    .command('init', 'Build new credentials.')
    .command('setup <useruuid>', 'Setup your user UUID.')
    .command('show', 'Show your credentials (for backup).')
    .command('restore <wifprivkey>', 'Restore credentials from backup.')
    .command('follow <nonce>', 'Wait an answer in the nonce.')
    .command('info', 'Retrieve general market info.')
    .command('newaddress [bech32] [currency]', 'Generate a new crypto deposit address.')
    .on('--help', function() {
        console.log('');
        console.log('Use walltime <command> -h to see more info about each command.');
        console.log('');
        console.log('To be able to use some commands, you have to set the system environment variable WT_SECRET to a secret that will be used to encrypt your credentials on disk. To keep it safe, it is recommended to clear this variable later.');
        console.log('');
        console.log('On Linux, use:');
        console.log('');
        console.log('\texport WT_SECRET=<yoursecret>');
        console.log('');
        console.log('On Windows, use:');
        console.log('');
        console.log('\tset WT_SECRET=<yoursecret>');
        console.log('');
    })
    .parse(process.argv);
