#!/usr/bin/env node

'use strict';
const program = require('commander');

if (typeof localStorage === "undefined" || localStorage === null) {
    var LocalStorage = require('node-localstorage').LocalStorage;
    var localStorage = new LocalStorage('./db');
}

const btc = require('bitcore-lib');
const ee = require('easy-encryption');

program
    .option('-t, --testnet', 'create a testnet credential')
    .option('-j, --json', 'return in json format')
    .option('-f, --force', 'force regenerate (overwrite) credentials (CAUTION!)')
    .option('-P, --privkey', 'show unencrypted private key on screen (CAUTION!)')
    .description('Build new credentials. Use it only in the very FIRST time. The credentials are kept saved on disk.')
    .parse(process.argv);

var password = process.env.WT_SECRET;

if (!password) {
    if (program.json) {
        console.log(JSON.stringify({'error' : true}));
    } else {
        console.error('Please, set the WT_SECRET env variable. It is required to encrypt your credentials on disk.');
    }
} else {
    var network;

    if (program.testnet) {
        network = btc.Networks.testnet;
    } else {
        network = btc.Networks.livenet;
    }

    if (localStorage.getItem(network + '.pub') && !program.force) {
        if (program.json) {
            console.log(JSON.stringify({'error': true}));
        } else {
            console.error('You already have stored credentials. Use -f to force overwrite.');
        }
    } else {
        if (localStorage.getItem(network + '.pub') && !program.json) {
            console.warn('[WARN] The credentials will be overwritten!');
        }

        if (!program.json) {
            console.log('Generating your credentials...');
        }

        var privateKey = new btc.PrivateKey();
        var address = privateKey.toAddress(network);

        var decryptedPrivateKey = privateKey.toWIF();

        if (!program.json) {
            console.log('');
            console.log('Done! Now, please inform the following address to our 24h support in https://m.me/walltime.info and identify yourself.');
            console.log('*** IMPORTANT: You will receive from our support an UUID and you have to call "walltime setup <UUID>" before call some commands.');
            console.log('==========================================');
            console.log(address.toString());
            console.log('==========================================');

            if (program.privkey) {
                console.log('');
                console.log('As requested, follow your unencrypted private key, BE CAREFUL:');
                console.log('==========================================');
                console.log(decryptedPrivateKey);
                console.log('==========================================');
                console.log('');
            }
        }

        if (program.json) {
            var result = {};
            result['address'] = address.toString();

            if (program.privkey) {
                result['privkey'] = decryptedPrivateKey;
            }

            console.log(JSON.stringify(result));
        }

        localStorage.setItem(network + '.pub', ee.encrypt(password, address.toString()));
        localStorage.setItem(network + '.sec', ee.encrypt(password, decryptedPrivateKey));
    }
}