#!/usr/bin/env node

'use strict';
const program = require('commander');

if (typeof localStorage === "undefined" || localStorage === null) {
    var LocalStorage = require('node-localstorage').LocalStorage;
    var localStorage = new LocalStorage('./db');
}

const btc = require('bitcore-lib');
const bip38 = require('bip38');
const wif = require('wif');
const ee = require('easy-encryption');

program
    .option('-t, --testnet', 'use testnet')
    .option('-j, --json', 'return in json format')
    .option('-f, --force', 'force regenerate (overwrite) credentials (CAUTION!)')
    .parse(process.argv);

var privkey = program.args[0];
var password = process.env.WT_SECRET;

if (!privkey || !password) {
    if (program.json) {
        console.log(JSON.stringify({'error' : true}));
    } else {
        console.error('A privkey and the env variable WT_SECRET are required to restore your credentials.');
    }
} else {
    var network;

    if (program.testnet) {
        network = btc.Networks.testnet;
    } else {
        network = btc.Networks.livenet;
    }

    if (localStorage.getItem(network + '.pub') && !program.force) {
        if (program.json) {
            console.log(JSON.stringify({'error': true}));
        } else {
            console.error('You already have stored credentials. Use -f to force overwrite.');
        }
    } else {
        if (localStorage.getItem(network + '.pub') && !program.json) {
            console.warn('[WARN] The credentials will be overwritten!');
        }

        if (!program.json) {
            console.log('Restoring your credentials... ');
        }

        var privateKey = btc.PrivateKey.fromWIF(privkey);
        var address = privateKey.toAddress(network);

        const privateKeyDecoded = wif.decode(privateKey.toWIF());
        var privateKeyEncrypted = bip38.encrypt(
            privateKeyDecoded.privateKey, privateKeyDecoded.compressed, password);

        if (!program.json) {
            console.log('');
            console.log('Done! Now, please inform the following address to our 24h support in https://m.me/walltime.info and identify yourself.');
            console.log('==========================================');
            console.log(address.toString());
            console.log('==========================================');
            console.log('');
            console.log('Please, backup your encrypted private key:');
            console.log('==========================================');
            console.log(privateKeyEncrypted);
            console.log('==========================================');
            console.log('');
        }

        if (program.json) {
            var result = {};
            result['address'] = address.toString();
            result['bip38_privkey'] = privateKeyEncrypted;
            console.log(JSON.stringify(result));
        }

        localStorage.setItem(network + '.pub', ee.encrypt(password, address.toString()));
        localStorage.setItem(network + '.sec', ee.encrypt(password, privateKeyEncrypted));
    }
}